#pragma once

#include <boost/preprocessor/stringize.hpp>

#define PROGRAM_NAME  "SD Mod Manager"
#define PROGRAM_ALIAS "The Sparrow"

#define PROGRAM_VERSION_MAJOR 0
#define PROGRAM_VERSION_MINOR 98
#define PROGRAM_VERSION_PATCH 3

#define PROGRAM_VERSION_BASE \
	BOOST_PP_STRINGIZE(PROGRAM_VERSION_MAJOR) "." BOOST_PP_STRINGIZE(PROGRAM_VERSION_MINOR) "." BOOST_PP_STRINGIZE(PROGRAM_VERSION_PATCH)

#define PROGRAM_VERSION PROGRAM_VERSION_BASE ".alpha"
